package internal

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/GoCodeAlone/workflow-plugin-ci-generator/internal/contracts"
	"github.com/GoCodeAlone/workflow-plugin-ci-generator/internal/platforms"
	sdk "github.com/GoCodeAlone/workflow/plugin/external/sdk"
)

// testdataConfig is the path to the representative workflow config used in
// cigen integration tests.
const testdataConfig = "testdata/app.yaml"

func TestExecuteCIGenerateTyped(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{
			ProjectName:   "typed-project",
			DefaultBranch: "main",
		},
		Input: &contracts.CIGenerateInput{
			Platform:    PlatformGitHubActions,
			OutputDir:   outputDir,
			InfraConfig: testdataConfig,
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil {
		t.Fatal("expected typed output")
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected output error: %s", result.Output.Error)
	}
	if result.Output.Platform != PlatformGitHubActions {
		t.Fatalf("expected platform %s, got %s", PlatformGitHubActions, result.Output.Platform)
	}
	if result.Output.FileCount == 0 {
		t.Fatal("expected generated files")
	}
	for _, written := range result.Output.FilesWritten {
		if _, err := os.Stat(written); err != nil {
			t.Fatalf("expected generated file %s: %v", written, err)
		}
		if !filepath.IsAbs(written) {
			t.Fatalf("expected absolute generated file path, got %s", written)
		}
	}
}

// TestExecuteCIGenerateGitHubActions_CigenMarkers verifies that github_actions
// output is generated by the cigen smart analyzer (not the old template).
// The representative config (testdata/app.yaml) has env_vars_secret
// (APP_DB_URL, APP_SECRET) and ci.migrations, so the rendered workflow must
// contain:
//   - a ${{ secrets.APP_DB_URL }} env binding (cigen secrets block)
//   - a "wfctl migrations up" step (cigen migrations step)
//   - no old "build.yml" / "deploy.yml" split (cigen renders a single file)
func TestExecuteCIGenerateGitHubActions_CigenMarkers(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformGitHubActions,
			OutputDir:     outputDir,
			InfraConfig:   testdataConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}
	if result.Output.FileCount == 0 {
		t.Fatal("expected at least one file written")
	}

	// Read all generated file contents.
	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw) + "\n"
	}
	t.Logf("generated github_actions output:\n%s", combined)

	// cigen renders secrets as job-level env: blocks using ${{ secrets.NAME }}.
	// APP_DB_URL comes from env_vars_secret in the testdata config.
	cigenSecretMarkers := []string{
		"${{ secrets.APP_DB_URL }}",
		"${{ secrets.APP_SECRET }}",
	}
	for _, marker := range cigenSecretMarkers {
		if !strings.Contains(combined, marker) {
			t.Errorf("github_actions: cigen marker %q not found in output", marker)
		}
	}

	// cigen renders a "wfctl migrations up" step when ci.migrations is present.
	if !strings.Contains(combined, "wfctl migrations up") {
		t.Errorf("github_actions: expected cigen migrations step 'wfctl migrations up' not found")
	}

	// The old template produced build.yml + deploy.yml. cigen renders a single
	// workflow file. The old-template-only string "name: Build" (from build.yml)
	// must NOT appear in cigen output.
	if strings.Contains(combined, "name: Build\n") {
		t.Errorf("github_actions: found old-template marker 'name: Build' — cigen should not render that")
	}
}

// TestExecuteCIGenerateGitLabCI_CigenMarkers verifies that gitlab_ci output is
// generated by the cigen smart analyzer (not the old template).
func TestExecuteCIGenerateGitLabCI_CigenMarkers(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformGitLabCI,
			OutputDir:     outputDir,
			InfraConfig:   testdataConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}

	// cigen renders a single .gitlab-ci.yml
	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw)
	}
	t.Logf("generated gitlab_ci output:\n%s", combined)

	// cigen emits a WFCTL_VERSION variable and uses `wfctl infra apply --config`.
	if !strings.Contains(combined, "WFCTL_VERSION") {
		t.Errorf("gitlab_ci: cigen marker 'WFCTL_VERSION' not found in output")
	}
	// cigen renders migrations as `wfctl migrations up`.
	if !strings.Contains(combined, "wfctl migrations up") {
		t.Errorf("gitlab_ci: expected cigen migrations step 'wfctl migrations up' not found")
	}
	// Old template emitted "image: golang:1.26" at the top level — cigen does not.
	if strings.Contains(combined, "image: golang:1.26") {
		t.Errorf("gitlab_ci: found old-template marker 'image: golang:1.26' — cigen should not render that")
	}
}

// TestExecuteCIGenerateJenkins_TemplateUnchanged verifies that jenkins output
// still comes from the template generator (unchanged).
func TestExecuteCIGenerateJenkins_TemplateUnchanged(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformJenkins,
			OutputDir:     outputDir,
			InfraConfig:   "infra.yaml",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}

	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw)
	}

	// Jenkins template produces a declarative Jenkinsfile.
	if !strings.Contains(combined, "pipeline {") {
		t.Errorf("jenkins: expected 'pipeline {' from template generator")
	}
	if !strings.Contains(combined, "stage('Checkout')") {
		t.Errorf("jenkins: expected 'stage('Checkout')' from template generator")
	}
}

// TestExecuteCIGenerateCircleCI_TemplateUnchanged verifies that circleci output
// still comes from the template generator (unchanged).
func TestExecuteCIGenerateCircleCI_TemplateUnchanged(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformCircleCI,
			OutputDir:     outputDir,
			InfraConfig:   "infra.yaml",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}

	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw)
	}

	// CircleCI template produces version: 2.1 with orbs.
	if !strings.Contains(combined, "version: 2.1") {
		t.Errorf("circleci: expected 'version: 2.1' from template generator")
	}
	if !strings.Contains(combined, "orbs:") {
		t.Errorf("circleci: expected 'orbs:' from template generator")
	}
}

func TestExecuteCIGenerateTypedValidation(t *testing.T) {
	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input:  &contracts.CIGenerateInput{},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil || result.Output.Error != "platform is required" {
		t.Fatalf("expected platform validation error, got %#v", result)
	}
}

func TestExecuteCIGenerateRejectsUnsafeGeneratedPath(t *testing.T) {
	restore := registerTestGenerator(t, "unsafe", staticGenerator{
		files: map[string]string{"../escape.yml": "bad"},
	})
	defer restore()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:  "unsafe",
			OutputDir: t.TempDir(),
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil || result.Output.Error == "" {
		t.Fatalf("expected unsafe path error, got %#v", result)
	}
}

func TestExecuteCIGenerateSortsFilesWritten(t *testing.T) {
	outputDir := t.TempDir()
	restore := registerTestGenerator(t, "static", staticGenerator{
		files: map[string]string{
			"z.yml": "z",
			"a.yml": "a",
		},
	})
	defer restore()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:  "static",
			OutputDir: outputDir,
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	want := []string{
		filepath.Join(outputDir, "a.yml"),
		filepath.Join(outputDir, "z.yml"),
	}
	if len(result.Output.FilesWritten) != len(want) {
		t.Fatalf("FilesWritten length = %d, want %d", len(result.Output.FilesWritten), len(want))
	}
	for i := range want {
		if result.Output.FilesWritten[i] != want[i] {
			t.Fatalf("FilesWritten[%d] = %q, want %q", i, result.Output.FilesWritten[i], want[i])
		}
	}
}

type staticGenerator struct {
	files map[string]string
}

func (g staticGenerator) Generate(_ platforms.Options) (map[string]string, error) {
	return g.files, nil
}

// registerTestGenerator registers a test generator in registry + knownPlatforms,
// and removes it on cleanup.
func registerTestGenerator(t *testing.T, platform string, generator Generator) func() {
	t.Helper()
	origGen, genExisted := registry[platform]
	origKnown := knownPlatforms[platform]
	registry[platform] = func() Generator { return generator }
	knownPlatforms[platform] = true
	return func() {
		if genExisted {
			registry[platform] = origGen
		} else {
			delete(registry, platform)
		}
		if origKnown {
			knownPlatforms[platform] = true
		} else {
			delete(knownPlatforms, platform)
		}
	}
}
