package internal

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/GoCodeAlone/workflow-plugin-ci-generator/internal/contracts"
	sdk "github.com/GoCodeAlone/workflow/plugin/external/sdk"
)

// testdataConfig is the path to the representative workflow config used in
// cigen integration tests.
const testdataConfig = "testdata/app.yaml"

func TestExecuteCIGenerateTyped(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{
			ProjectName:   "typed-project",
			DefaultBranch: "main",
		},
		Input: &contracts.CIGenerateInput{
			Platform:    PlatformGitHubActions,
			OutputDir:   outputDir,
			InfraConfig: testdataConfig,
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil {
		t.Fatal("expected typed output")
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected output error: %s", result.Output.Error)
	}
	if result.Output.Platform != PlatformGitHubActions {
		t.Fatalf("expected platform %s, got %s", PlatformGitHubActions, result.Output.Platform)
	}
	if result.Output.FileCount == 0 {
		t.Fatal("expected generated files")
	}
	for _, written := range result.Output.FilesWritten {
		if _, err := os.Stat(written); err != nil {
			t.Fatalf("expected generated file %s: %v", written, err)
		}
		if !filepath.IsAbs(written) {
			t.Fatalf("expected absolute generated file path, got %s", written)
		}
	}
}

// TestExecuteCIGenerateGitHubActions_CigenMarkers verifies that github_actions
// output is generated by the cigen smart analyzer (not the old template).
// The representative config (testdata/app.yaml) has env_vars_secret
// (APP_DB_URL, APP_SECRET) and ci.migrations, so the rendered workflow must
// contain:
//   - a ${{ secrets.APP_DB_URL }} env binding (cigen secrets block)
//   - a "wfctl migrations up" step (cigen migrations step)
//   - no old "build.yml" / "deploy.yml" split (cigen renders a single file)
func TestExecuteCIGenerateGitHubActions_CigenMarkers(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformGitHubActions,
			OutputDir:     outputDir,
			InfraConfig:   testdataConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}
	if result.Output.FileCount == 0 {
		t.Fatal("expected at least one file written")
	}

	// Read all generated file contents.
	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw) + "\n"
	}
	t.Logf("generated github_actions output:\n%s", combined)

	// cigen renders secrets as job-level env: blocks using ${{ secrets.NAME }}.
	// APP_DB_URL comes from env_vars_secret in the testdata config.
	cigenSecretMarkers := []string{
		"${{ secrets.APP_DB_URL }}",
		"${{ secrets.APP_SECRET }}",
	}
	for _, marker := range cigenSecretMarkers {
		if !strings.Contains(combined, marker) {
			t.Errorf("github_actions: cigen marker %q not found in output", marker)
		}
	}

	// cigen renders a "wfctl migrations up" step when ci.migrations is present.
	if !strings.Contains(combined, "wfctl migrations up") {
		t.Errorf("github_actions: expected cigen migrations step 'wfctl migrations up' not found")
	}

	// The old template produced build.yml + deploy.yml. cigen renders a single
	// workflow file. The old-template-only string "name: Build" (from build.yml)
	// must NOT appear in cigen output.
	if strings.Contains(combined, "name: Build\n") {
		t.Errorf("github_actions: found old-template marker 'name: Build' — cigen should not render that")
	}
}

func TestExecuteCIGenerateGitHubActionsRunnerSelection(t *testing.T) {
	t.Run("default", func(t *testing.T) {
		combined := executeAndReadCombined(t, PlatformGitHubActions)
		if !strings.Contains(combined, "runs-on: ubuntu-latest") {
			t.Fatalf("expected default runner ubuntu-latest, output:\n%s", combined)
		}
	})

	t.Run("override", func(t *testing.T) {
		outputDir := t.TempDir()
		result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
			Config: &contracts.CIGenerateConfig{},
			Input: &contracts.CIGenerateInput{
				Platform:    PlatformGitHubActions,
				OutputDir:   outputDir,
				InfraConfig: testdataConfig,
				Runner:      "self-hosted",
			},
		})
		if err != nil {
			t.Fatalf("ExecuteCIGenerate: %v", err)
		}
		if result.Output.Error != "" {
			t.Fatalf("unexpected error: %s", result.Output.Error)
		}
		if result.Output.FileCount == 0 {
			t.Fatal("expected generated files")
		}

		combined := ""
		for _, written := range result.Output.FilesWritten {
			raw, err := os.ReadFile(written)
			if err != nil {
				t.Fatalf("read %s: %v", written, err)
			}
			combined += string(raw) + "\n"
		}
		if !strings.Contains(combined, "runs-on: self-hosted") {
			t.Fatalf("expected explicit runner override self-hosted, output:\n%s", combined)
		}
		if strings.Contains(combined, "runs-on: ubuntu-latest") {
			t.Fatalf("default runner leaked into override output:\n%s", combined)
		}
	})
}

// TestExecuteCIGenerateGitLabCI_CigenMarkers verifies that gitlab_ci output is
// generated by the cigen smart analyzer (not the old template).
func TestExecuteCIGenerateGitLabCI_CigenMarkers(t *testing.T) {
	outputDir := t.TempDir()

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformGitLabCI,
			OutputDir:     outputDir,
			InfraConfig:   testdataConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}

	// cigen renders a single .gitlab-ci.yml
	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw)
	}
	t.Logf("generated gitlab_ci output:\n%s", combined)

	// cigen emits a WFCTL_VERSION variable and uses `wfctl infra apply --config`.
	if !strings.Contains(combined, "WFCTL_VERSION") {
		t.Errorf("gitlab_ci: cigen marker 'WFCTL_VERSION' not found in output")
	}
	// cigen renders migrations as `wfctl migrations up`.
	if !strings.Contains(combined, "wfctl migrations up") {
		t.Errorf("gitlab_ci: expected cigen migrations step 'wfctl migrations up' not found")
	}
	// Old template emitted "image: golang:1.26" at the top level — cigen does not.
	if strings.Contains(combined, "image: golang:1.26") {
		t.Errorf("gitlab_ci: found old-template marker 'image: golang:1.26' — cigen should not render that")
	}
}

// TestExecuteCIGenerateGitHubActions_AbsoluteConfigRendersRepoRelative verifies
// that when infra_config is an absolute path (outside the repo checkout), the
// rendered GitHub Actions workflow references a clean repo-relative config path
// (base filename) — never an absolute path or one with a leading "/" or "..".
// This guards against cigen.Analyze's filepath.Rel(cwd, abs) leaking an
// out-of-tree path into the `--config` steps and `paths:` trigger filter.
func TestExecuteCIGenerateGitHubActions_AbsoluteConfigRendersRepoRelative(t *testing.T) {
	// Copy the representative config to an absolute tmp path outside the repo.
	src, err := os.ReadFile(testdataConfig)
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	tmpDir := t.TempDir()
	absConfig := filepath.Join(tmpDir, "deploy.yaml")
	if err := os.WriteFile(absConfig, src, 0o644); err != nil {
		t.Fatalf("write tmp config: %v", err)
	}
	if !filepath.IsAbs(absConfig) {
		t.Fatalf("expected absolute config path, got %s", absConfig)
	}

	outputDir := t.TempDir()
	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      PlatformGitHubActions,
			OutputDir:     outputDir,
			InfraConfig:   absConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result.Output.Error != "" {
		t.Fatalf("unexpected error: %s", result.Output.Error)
	}

	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw)
	}
	t.Logf("generated github_actions output (absolute infra_config):\n%s", combined)

	// The config alias must collapse to the base filename.
	if !strings.Contains(combined, "--config 'deploy.yaml'") {
		t.Errorf("expected '--config '\\''deploy.yaml'\\''' (repo-relative base), output:\n%s", combined)
	}
	// The paths: trigger filter must reference the relative base name.
	if !strings.Contains(combined, "- 'deploy.yaml'") {
		t.Errorf("expected paths: entry \"- 'deploy.yaml'\", output:\n%s", combined)
	}
	// The absolute tmp path must NOT leak into the rendered workflow.
	if strings.Contains(combined, absConfig) {
		t.Errorf("absolute config path %q leaked into rendered output:\n%s", absConfig, combined)
	}
	// No "/" prefixed --config and no ".." escaping path.
	if strings.Contains(combined, "--config '/") {
		t.Errorf("rendered output contains an absolute --config path:\n%s", combined)
	}
	if strings.Contains(combined, "..") {
		t.Errorf("rendered output contains a '..' escaping path:\n%s", combined)
	}
}

// TestCleanConfigAlias exercises the alias normalization directly.
func TestCleanConfigAlias(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"empty", "", ""},
		{"relative clean", "infra.yaml", "infra.yaml"},
		{"relative nested", "deploy/app.yaml", "deploy/app.yaml"},
		{"relative dot prefix", "./infra.yaml", "infra.yaml"},
		{"absolute collapses to base", "/tmp/build123/deploy.yaml", "deploy.yaml"},
		{"parent escape collapses to base", "../sibling/deploy.yaml", "deploy.yaml"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := cleanConfigAlias(tc.in); got != tc.want {
				t.Errorf("cleanConfigAlias(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// executeAndReadCombined runs ExecuteCIGenerate for a platform against the
// representative testdata config and returns the concatenated written-file bytes.
// This drives the REAL plugin entry point (acceptance #2 for #804).
func executeAndReadCombined(t *testing.T, platform string) string {
	t.Helper()
	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:      platform,
			OutputDir:     t.TempDir(),
			InfraConfig:   testdataConfig,
			ProjectName:   "my-app",
			DefaultBranch: "main",
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate(%s): %v", platform, err)
	}
	if result.Output.Error != "" {
		t.Fatalf("%s: unexpected error: %s", platform, result.Output.Error)
	}
	if result.Output.FileCount == 0 {
		t.Fatalf("%s: expected at least one file written", platform)
	}
	combined := ""
	for _, written := range result.Output.FilesWritten {
		raw, err := os.ReadFile(written)
		if err != nil {
			t.Fatalf("read %s: %v", written, err)
		}
		combined += string(raw) + "\n"
	}
	return combined
}

// assertNoRetiredStages asserts the retired, non-config-derived stages (ADR 0044)
// do not appear in cigen-generated output.
func assertNoRetiredStages(t *testing.T, platform, combined string) {
	t.Helper()
	for _, banned := range []string{"go test ./...", "wfctl deploy --image", "docker build", "docker push", "wfctl ci run --phase migrate"} {
		if strings.Contains(combined, banned) {
			t.Errorf("%s: found retired legacy marker %q — cigen should not render that", platform, banned)
		}
	}
}

// TestExecuteCIGenerateJenkins_CigenMarkers verifies jenkins output is generated
// by the cigen smart analyzer (not the retired template generator).
func TestExecuteCIGenerateJenkins_CigenMarkers(t *testing.T) {
	combined := executeAndReadCombined(t, PlatformJenkins)
	for _, marker := range []string{
		"pipeline {",
		"Requires a Jenkins Multibranch Pipeline",
		"credentials('APP_DB_URL')",
		"wfctl migrations up",
		"wfctl infra apply",
		"curl --fail --max-time 30 'https://myapp.example.com/healthz'", // smoke
	} {
		if !strings.Contains(combined, marker) {
			t.Errorf("jenkins: cigen marker %q not found in output", marker)
		}
	}
	assertNoRetiredStages(t, "jenkins", combined)
	// The old template emitted stage('Checkout'); cigen does not.
	if strings.Contains(combined, "stage('Checkout')") {
		t.Errorf("jenkins: found old-template marker stage('Checkout')")
	}
}

// TestExecuteCIGenerateCircleCI_CigenMarkers verifies circleci output is
// generated by the cigen smart analyzer (not the retired template generator).
func TestExecuteCIGenerateCircleCI_CigenMarkers(t *testing.T) {
	combined := executeAndReadCombined(t, PlatformCircleCI)
	for _, marker := range []string{
		"version: 2.1",
		"requires:",
		"APP_DB_URL", // secret referenced (project env var header)
		"wfctl migrations up",
		"wfctl infra apply",
		"curl --fail --max-time 30 'https://myapp.example.com/healthz'", // smoke
	} {
		if !strings.Contains(combined, marker) {
			t.Errorf("circleci: cigen marker %q not found in output", marker)
		}
	}
	assertNoRetiredStages(t, "circleci", combined)
	// The old template emitted `orbs:`; cigen does not.
	if strings.Contains(combined, "orbs:") {
		t.Errorf("circleci: found old-template marker 'orbs:'")
	}
}

func TestExecuteCIGenerateTypedValidation(t *testing.T) {
	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input:  &contracts.CIGenerateInput{},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil || result.Output.Error != "platform is required" {
		t.Fatalf("expected platform validation error, got %#v", result)
	}
}

func TestExecuteCIGenerateValidatesRenderedArtifacts(t *testing.T) {
	outputDir := t.TempDir()
	planPath := filepath.Join(outputDir, "bad-plan.json")
	if err := os.WriteFile(planPath, []byte(`{"project":"bad","phases":[]}`), 0o644); err != nil {
		t.Fatalf("write bad plan: %v", err)
	}

	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:  PlatformGitHubActions,
			OutputDir: outputDir,
			FromPlan:  planPath,
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if result == nil || result.Output == nil {
		t.Fatal("expected typed output")
	}
	if !strings.Contains(result.Output.Error, "cigen validate github_actions") {
		t.Fatalf("expected rendered validation error, got %#v", result.Output.Error)
	}
}

// TestValidateRelativeOutputPath exercises the path-safety guard directly (the
// registry-injection seam it used to be tested through was removed with the
// template generators in #804).
func TestValidateRelativeOutputPath(t *testing.T) {
	for _, bad := range []string{"../escape.yml", "a/../../b.yml", "/abs/path.yml", ""} {
		if err := validateRelativeOutputPath(bad); err == nil {
			t.Errorf("expected error for unsafe path %q", bad)
		}
	}
	for _, good := range []string{"Jenkinsfile", ".circleci/config.yml", ".github/workflows/ci.yml"} {
		if err := validateRelativeOutputPath(good); err != nil {
			t.Errorf("unexpected error for safe path %q: %v", good, err)
		}
	}
}

// TestExecuteCIGenerateSortsFilesWritten asserts FilesWritten is sorted on a real
// cigen render. Each renderer writes a single file today, so this asserts the
// sort invariant holds (and documents it) rather than exercising a multi-file
// permutation that no current renderer produces.
func TestExecuteCIGenerateSortsFilesWritten(t *testing.T) {
	result, err := ExecuteCIGenerate(context.Background(), sdk.TypedStepRequest[*contracts.CIGenerateConfig, *contracts.CIGenerateInput]{
		Config: &contracts.CIGenerateConfig{},
		Input: &contracts.CIGenerateInput{
			Platform:    PlatformGitHubActions,
			OutputDir:   t.TempDir(),
			InfraConfig: testdataConfig,
		},
	})
	if err != nil {
		t.Fatalf("ExecuteCIGenerate: %v", err)
	}
	if !sort.StringsAreSorted(result.Output.FilesWritten) {
		t.Errorf("FilesWritten not sorted: %v", result.Output.FilesWritten)
	}
}
