// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/ci_generator.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CIGenerateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	InfraConfig   string                 `protobuf:"bytes,3,opt,name=infra_config,json=infraConfig,proto3" json:"infra_config,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Runner        string                 `protobuf:"bytes,5,opt,name=runner,proto3" json:"runner,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,6,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIGenerateConfig) Reset() {
	*x = CIGenerateConfig{}
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIGenerateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIGenerateConfig) ProtoMessage() {}

func (x *CIGenerateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIGenerateConfig.ProtoReflect.Descriptor instead.
func (*CIGenerateConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ci_generator_proto_rawDescGZIP(), []int{0}
}

func (x *CIGenerateConfig) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CIGenerateConfig) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *CIGenerateConfig) GetInfraConfig() string {
	if x != nil {
		return x.InfraConfig
	}
	return ""
}

func (x *CIGenerateConfig) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CIGenerateConfig) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *CIGenerateConfig) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

type CIGenerateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	InfraConfig   string                 `protobuf:"bytes,3,opt,name=infra_config,json=infraConfig,proto3" json:"infra_config,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Runner        string                 `protobuf:"bytes,5,opt,name=runner,proto3" json:"runner,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,6,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIGenerateInput) Reset() {
	*x = CIGenerateInput{}
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIGenerateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIGenerateInput) ProtoMessage() {}

func (x *CIGenerateInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIGenerateInput.ProtoReflect.Descriptor instead.
func (*CIGenerateInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ci_generator_proto_rawDescGZIP(), []int{1}
}

func (x *CIGenerateInput) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CIGenerateInput) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *CIGenerateInput) GetInfraConfig() string {
	if x != nil {
		return x.InfraConfig
	}
	return ""
}

func (x *CIGenerateInput) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *CIGenerateInput) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *CIGenerateInput) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

type CIGenerateOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	OutputDir     string                 `protobuf:"bytes,2,opt,name=output_dir,json=outputDir,proto3" json:"output_dir,omitempty"`
	FilesWritten  []string               `protobuf:"bytes,3,rep,name=files_written,json=filesWritten,proto3" json:"files_written,omitempty"`
	FileCount     int32                  `protobuf:"varint,4,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIGenerateOutput) Reset() {
	*x = CIGenerateOutput{}
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIGenerateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIGenerateOutput) ProtoMessage() {}

func (x *CIGenerateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_ci_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIGenerateOutput.ProtoReflect.Descriptor instead.
func (*CIGenerateOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_ci_generator_proto_rawDescGZIP(), []int{2}
}

func (x *CIGenerateOutput) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CIGenerateOutput) GetOutputDir() string {
	if x != nil {
		return x.OutputDir
	}
	return ""
}

func (x *CIGenerateOutput) GetFilesWritten() []string {
	if x != nil {
		return x.FilesWritten
	}
	return nil
}

func (x *CIGenerateOutput) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *CIGenerateOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_ci_generator_proto protoreflect.FileDescriptor

const file_internal_contracts_ci_generator_proto_rawDesc = "" +
	"\n" +
	"%internal/contracts/ci_generator.proto\x12 workflow.plugins.ci_generator.v1\"\xd2\x01\n" +
	"\x10CIGenerateConfig\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12!\n" +
	"\finfra_config\x18\x03 \x01(\tR\vinfraConfig\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x16\n" +
	"\x06runner\x18\x05 \x01(\tR\x06runner\x12%\n" +
	"\x0edefault_branch\x18\x06 \x01(\tR\rdefaultBranch\"\xd1\x01\n" +
	"\x0fCIGenerateInput\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12!\n" +
	"\finfra_config\x18\x03 \x01(\tR\vinfraConfig\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12\x16\n" +
	"\x06runner\x18\x05 \x01(\tR\x06runner\x12%\n" +
	"\x0edefault_branch\x18\x06 \x01(\tR\rdefaultBranch\"\xa7\x01\n" +
	"\x10CIGenerateOutput\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"output_dir\x18\x02 \x01(\tR\toutputDir\x12#\n" +
	"\rfiles_written\x18\x03 \x03(\tR\ffilesWritten\x12\x1d\n" +
	"\n" +
	"file_count\x18\x04 \x01(\x05R\tfileCount\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorBRZPgithub.com/GoCodeAlone/workflow-plugin-ci-generator/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_ci_generator_proto_rawDescOnce sync.Once
	file_internal_contracts_ci_generator_proto_rawDescData []byte
)

func file_internal_contracts_ci_generator_proto_rawDescGZIP() []byte {
	file_internal_contracts_ci_generator_proto_rawDescOnce.Do(func() {
		file_internal_contracts_ci_generator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_ci_generator_proto_rawDesc), len(file_internal_contracts_ci_generator_proto_rawDesc)))
	})
	return file_internal_contracts_ci_generator_proto_rawDescData
}

var file_internal_contracts_ci_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_contracts_ci_generator_proto_goTypes = []any{
	(*CIGenerateConfig)(nil), // 0: workflow.plugins.ci_generator.v1.CIGenerateConfig
	(*CIGenerateInput)(nil),  // 1: workflow.plugins.ci_generator.v1.CIGenerateInput
	(*CIGenerateOutput)(nil), // 2: workflow.plugins.ci_generator.v1.CIGenerateOutput
}
var file_internal_contracts_ci_generator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_ci_generator_proto_init() }
func file_internal_contracts_ci_generator_proto_init() {
	if File_internal_contracts_ci_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_ci_generator_proto_rawDesc), len(file_internal_contracts_ci_generator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_ci_generator_proto_goTypes,
		DependencyIndexes: file_internal_contracts_ci_generator_proto_depIdxs,
		MessageInfos:      file_internal_contracts_ci_generator_proto_msgTypes,
	}.Build()
	File_internal_contracts_ci_generator_proto = out.File
	file_internal_contracts_ci_generator_proto_goTypes = nil
	file_internal_contracts_ci_generator_proto_depIdxs = nil
}
